testbot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 25

  # Position controllers
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    # a xacro like file to generate this would be nice TBD
    joint: joint_1
    pid: {p:100.0, i: 0.01, d:10.0}

  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    # a xacro like file to generate this would be nice TBD
    joint: joint_2
    pid: {p:100.0, i: 0.01, d:10.0}

  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    # a xacro like file to generate this would be nice TBD
    joint: joint_3
    pid: {p:100.0, i: 0.01, d:10.0}

  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    # a xacro like file to generate this would be nice TBD
    joint: joint_4
    pid: {p:100.0, i: 0.01, d:10.0}

