<?xml version="1.0"?>
<robot name="testbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- http://answers.ros.org/question/38956/pass-parameters-to-xacro-in-launch-file/ -->
<xacro:property name="seg_length" value="0.2" />
<xacro:property name="seg_width" value="0.15" />
<xacro:property name="seg_height" value="0.1" />


<xacro:macro name="segment" params="parent postfix length width height">
  <link name="link_${postfix}">
<!--    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${length} ${width} ${height}" />
      </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${length} ${width} ${height}" />
        </geometry>
    </visual>
   
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1.0" />
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
    </inertial>
    -->
  </link>

  <joint name="joint_${postfix}" type="revolute">
        <parent link="${parent}" />
        <child link="link_${postfix}" />
        <origin xyz="${length/2 + 0.05} 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="-0.5" upper="0.5" velocity="0.5" />
  </joint>

</xacro:macro>

<link name="base_link" />

<xacro:segment parent="base_link" postfix="1" length="${seg_length}" width="${seg_width}" height="${seg_height}" />
     <xacro:segment parent="link_1" postfix="2" length="${seg_length}" width="${seg_width}" height="${seg_height}" />
<xacro:segment parent="link_2" postfix="3" length="${seg_length}" width="${seg_width}" height="${seg_height}" />
<xacro:segment parent="link_3" postfix="4" length="${seg_length}" width="${seg_width}" height="${seg_height}" />
<!--
<xacro:segment parent="link_4" postfix="5" length="${seg_length}" width="${seg_width}" height="${seg_height}" />
<xacro:segment parent="link_5" postfix="6" length="${seg_length}" width="${seg_width}" height="${seg_height}" />
-->

</robot>
